let streetNum = [Math.floor(Math.random() * 10000 + 1)]
// This generates a number between 1 and 10000
let streetName = [
  "1st",
  "2nd",
  "3rd",
  "4th",
  "5th",
  "6th",
  "7th",
  "8th",
  "9th",
  "10th",
  "11th",
  "12th",
  "13th"
]
let cityName = [
  "Abbeville",
  "Aberdeen",
  "Aberdeen",
  "Aberdeen",
  "Aberdeen",
  "Abilene",
  "Abilene",
  "Abingdon",
  "Abington",
  "Abington",
  "Absecon",
  "Accokeek",
  "Acton",
  "Acushnet",
  "Acworth",
  "Ada",
  "Adams",
  "Addison",
  "Addison",
  "Adelanto",
  "Adelphi",
  "Adrian",
  "Affton",
  "Agawam",
  "Agoura Hills",
  "Ahuimanu",
  "Aiea",
  "Aiken",
  "Dallas",
  "Airmont",
  "Akron",
  "Alabaster",
  "Alachua",
  "Alameda",
  "Alamo",
  "Alamo",
  "Alamo Heights",
  "Alamogordo",
  "Alamosa",
  "Albany",
  "Albany",
  "Albany",
  "Albany",
  "Albemarle",
  "Albert Lea",
  "Albertville",
  "Albion",
  "Albion",
  "Albion",
  "Albuquerque"
]
let stateName = [
  "Alabama",
  "Alaska",
  "American Samoa",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "District Of Columbia",
  "Federated States Of Micronesia",
  "Florida",
  "Georgia",
  "Guam",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Marshall Islands",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Northern Mariana Islands",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Palau",
  "Pennsylvania",
  "Puerto Rico",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virgin Islands",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming"
]
let zip = Math.floor(Math.random() * 90000) + 10000
// This generates a zip between 10000 and 99999

console.log(
  `${streetNum} ${
    streetName[Math.floor(Math.random() * streetName.length)]
  } Street \ ${cityName[Math.floor(Math.random() * cityName.length)]} ${
    stateName[Math.floor(Math.random() * stateName.length)]
  }, ${zip}`
)

/** Math.floor(Math.random() * streetName.length)
 * This is generating a random number between 0 and the length of the array
 *  and rounds it down
 */
